version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cypress/base:10
    working_directory: ~/repo/echo-front

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Project
          command: npm run build
      - run:
          name: Run End-To-End Test
          command: npm run test:e2e
      - persist_to_workspace:
          root: ~/
          paths:
            - echo-front


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
