version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "./package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}

      - run: npm run build

      - run: npm run deploy
