version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10
    working_directory: ~/echo-front

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - echo-front
  
  test-e2e:
    docker:
      - image: cypress/base:10
    working_directory: ~/echo-front
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      # - run:
      #       name: Install Cypress
      #       command: npm run cypress:install
      # - run:
      #       name: Cypress End-To-End Test
      #       command: npm run test:ci
  
  deploy:
    docker:
      - image: node:latest
    working_directory: ~/echo-front
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Deploy to Edison Server
          command: npm run deploy

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - build
      - test-e2e:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - build
      #       - test-e2e
