version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:10
    working_directory: ~/echo-front

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
            - /root/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - echo-front
            - /root/.cache
  
  test-e2e:
    docker:
      - image: cypress/base:10
    working_directory: ~/echo-front
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
            name: Cypress End-To-End Test
            command: npm run test:e2e

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-e2e:
          requires:
            - build
