version: 2.1

executors:
  default:
    working_directory: ~/project/echo-front
    docker:
      - image: cypress/base:10

jobs:
  install:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
  build:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run build
      - store_artifacts:
          path: ~/project/echo-front/dist
          destination: dist
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  test-e2e:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run test:ci
      - store_artifacts:
          path: ~/project/echo-front/tests/videos
          destination: tests/videos
      - store_artifacts:
          path: ~/project/echo-front/tests/screenshots
          destination: tests/screenshots
  deploy:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn run deploy

workflows:
  test-and-deploy:
    jobs:
      - install
      - test-e2e:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test-e2e
            - build
